### ISSUE TITLE
What does the /etc/default/zfs do?

### ISSUE THREAD

**Issue by TegarOk** [anatol/booster#181]
Im using Voidlinux, i dont have this file and i dont know what is this file do.
Can we ignore it? Change it into warning instead return being Error if it didnt exist? I make this file with blank space and no error after that.
It seems this file doesnt do anything important, at least i dont need this file to boot from dracut initramfs.
I think the file is in generator/generator.go

One more questions, is it support native encryption from ZFS? I cant bypass and got permission denied because the boot didnt ask pass for Encryption pool or volume.
I remember there is a  zfs_import_params, what does this config do?

**Comment by anatol** [comment]
Hi sorry for being late. It was added as it seems `zfs` binary was using it at Arch Linux. But we can ignore at the platforms that do not have this file.

**Comment by anatol** [comment]
I just pushed a fix to `wip` branch. Please try it and let me know if it works for you.

**Comment by anatol** [comment]
As for ZFS remote unlocking please see https://github.com/anatol/booster/issues/191

**Comment by TegarOk** [comment]
Sorry for the late response, im build & test it, its works. But still no luck with ZFS native encryption.

> As for ZFS remote unlocking please see #191

So im gonna closed the issue then & watch it there.
