### ISSUE TITLE
Failed to mount btrfs array

### ISSUE THREAD

**Issue by lucas-mior** [anatol/booster#283]
Related to #194.
`booster.yaml` is empty.
Kernel command line: `rd.luks.name=7675b74a-f03d-4aa5-ae60-b687a432a426=root1 rd.luks.name=e1400000-62b5-47cd-bfd1-2795ea331ace=root2 root=/dev/mapper/root1 rootflags=subvol=@`

When booting, after typing the first password, it immediately fails. I tried typing the password for the second drive afterwards, it says `Unlocking...` but then nothing happens.
```
Enter passphrase for root1: Unlocking...
Enter passphrase for root2: [   8.96973] BTRFS error (device dm-0): devid 2 uuid 885... is missing
[    8.96978] BTRFS error (device dm-0): failed to read the system array: -2
[    8.96987] BTRFS error (device dm-0): open_ctree failed: -2
[    8.96994] booster: mount(/dev/dm-0): no such file or directory
  Unlocking...
```

Related to that, when using mkinitcpio with the sd-encrypt hook, the same password is tried for subsequent drives, avoiding have to type the same password multiple times.

**Comment by anatol** [comment]
The #194 you mentioned is fixed now so it must be a different problem.

But if I understand you correctly you are using BTRFS on top of LVM volume? Could you please provide more information about your disk/LVM configuration? How did you create your layout?

**Comment by pilotstew** [comment]
If the two drives share the same passphrase this is fixed via #335. I created a qemu test for just this scenario. I haven't verified the case for two drives, different passphrases.

**Comment by pilotstew** [comment]
Following up on my earlier comment. The shared-passphrase variant of this is fixed by #335 (the in-boot passphrase cache plus serialized keyboard prompts), and is regression-tested by `TestLuksBtrfsRaid1` (two LUKS2 btrfs-RAID1 members, one prompt) and `TestPassphraseCache` (the #306 root+data case).

The remaining open question was the case in the original report: two btrfs members with **different** passphrases, where the cache can't help. I've now verified it with a dedicated test, `TestLuksBtrfsRaid1DistinctPass` — a btrfs RAID1 over two LUKS2 partitions with distinct passphrases. It passes: booster prompts for each member separately (serialized by `keyboardMu`, never interleaved), the cache does not wrongly substitute the first member's passphrase for the second, both unlock, and btrfs assembles. The test is order-independent (device discovery order is nondeterministic; it routes the right passphrase by the crypttab mapping name).

So the failure here appears resolved by #335 — the original symptom predates that fix. Both the shared- and distinct-passphrase paths are now covered. I think this can be closed. I can open a PR with the distinct-passphrase test if you'd like the coverage in-tree.

**Comment by thePrivacyFanatic** [comment]
@lucas-mior if this is solved for you could you close it?

**Comment by lucas-mior** [comment]
Sorry, it still does not work. I am using the latest booster version from github. My booster.yaml is empty. 
My systemd-boot config is:
```
title   Arch Linux (booster)
linux   /vmlinuz-linux
initrd  /booster-linux.img
options rd.luks.name=$LUKS1_UUID=root1
options rd.luks.name=$LUKS2_UUID=root2
options root=/dev/mapper/root1
options rootflags=subvol=@
options panic=30 kernel.sysrq=1 loglevel=6
options systemd.show_status=1
```

When booting:
```
Enter passphrase for root1: *
Unlocking...
```
And it just hangs.

**Comment by anatol** [comment]
Can you please enable debug logs https://github.com/anatol/booster/blob/master/docs/manpage.md#debugging as well as emergency shell so you can grab those logs easily. And then share the logs with us.

**Comment by pilotstew** [comment]
Thank you for posting your config. I am able to reproduce your error and I'll have a fix soon. `loglevel=6` hides the error. If you run it with `booster.log=console` or `loglevel=7` you'll probably see  "Waiting for multi-device btrfs…" 

Verify something for me @lucas-mior 

 `btrfs filesystem show /` should print your filesystem UUID replace your root= like this and let me know if it boots:

```
options rd.luks.name=$LUKS1_UUID=root1
options rd.luks.name=$LUKS2_UUID=root2
options root=UUID=<FS_UUID>
options rootflags=subvol=@
```

Whats happening here and I should have caught it the first time is that you declare `root=/dev/mapper/root1` which essentially means that during boot only that device gets registered for the btrfs root partition, The other is unknown, required and missing, BTRFS can't mount without all members, hangs... Supplying the FS-UUID should correctly identify each of the BTRFS root devices. your dev/mapper/ is a convention booster can and should support via `BTRFS_IOC_SCAN_DEV` but the quick fix for now is to use FS-UUID

**Comment by lucas-mior** [comment]
Yes, using the UUID for the btrfs FS works, thank you.

**Comment by pilotstew** [comment]
I'm working on adding `BTRFS_IOC_SCAN_DEV` which should provide more robust handling in the future.
